# Generated by Django 4.2.7 on 2023-11-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_payment_paid_for_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ID оплаты Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_for_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='оплата за курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_for_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lesson', verbose_name='оплата за урок'),
        ),
    ]
